{"resourceLogs":[{"resource":{"attributes":[{"key":"service.name","value":{"stringValue":"PragmatismWebApp.TelemetryService"}}]},"scopeLogs":[{"scope":{"name":"PragmatismWebApp.TelemetryService"},"logRecords":[{"timeUnixNano":"1744557180925656500","observedTimeUnixNano":"1744557180925656500","severityNumber":17,"severityText":"Error","body":{"stringValue":"ContainerManagerService.Start: {Type: ContainerManagerService_Retryable_FailedToRunTests, Message: Failed to run tests err:shared_helper.RunCmdAndGetStdFiles: {Type: SharedHelpers_Retryable_RunCommandFailed, Message: cmdHandle.Wait() failed: exit status 137, stdErr was returned to the upper layers}, stdErr:}"},"attributes":[{"key":"error.ErrorTrace","value":{"arrayValue":{"values":[{"stringValue":"ContainerManagerService_Retryable_FailedToRunTests"}]}}},{"key":"error.Origin","value":{"stringValue":"ContainerManagerService.Start"}},{"key":"error.Message","value":{"stringValue":"Failed to run tests err:shared_helper.RunCmdAndGetStdFiles: {Type: SharedHelpers_Retryable_RunCommandFailed, Message: cmdHandle.Wait() failed: exit status 137, stdErr was returned to the upper layers}, stdErr:"}}],"traceId":"","spanId":"","eventName":"ContainerManagerService_Retryable_FailedToRunTests"}]}],"schemaUrl":"https://opentelemetry.io/schemas/1.17.0"}]}
{"resourceLogs":[{"resource":{"attributes":[{"key":"service.name","value":{"stringValue":"PragmatismWebApp.TelemetryService"}}]},"scopeLogs":[{"scope":{"name":"PragmatismWebApp.TelemetryService"},"logRecords":[{"timeUnixNano":"1744557328784529700","observedTimeUnixNano":"1744557328784529700","severityNumber":17,"severityText":"Error","body":{"stringValue":"UsersModelService.UpdateSolvedTask: {Type: UsersModelService_Retryable_FailedToUpdateSolvedTask, Message: Failed to query database : pq: syntax error at or near \"NOTING\"}"},"attributes":[{"key":"error.ErrorTrace","value":{"arrayValue":{"values":[{"stringValue":"UsersModelService_Retryable_FailedToUpdateSolvedTask"},{"stringValue":"DBService_Retryable_FailedToQueryDatabase"}]}}},{"key":"error.Origin","value":{"stringValue":"UsersModelService.UpdateSolvedTask"}},{"key":"error.Message","value":{"stringValue":"Failed to query database : pq: syntax error at or near \"NOTING\""}}],"traceId":"","spanId":"","eventName":"UsersModelService_Retryable_FailedToUpdateSolvedTask"}]}],"schemaUrl":"https://opentelemetry.io/schemas/1.17.0"}]}
{"resourceLogs":[{"resource":{"attributes":[{"key":"service.name","value":{"stringValue":"PragmatismWebApp.TelemetryService"}}]},"scopeLogs":[{"scope":{"name":"PragmatismWebApp.TelemetryService"},"logRecords":[{"timeUnixNano":"1744558586098542300","observedTimeUnixNano":"1744558586098542300","severityNumber":17,"severityText":"Error","body":{"stringValue":"UsersModelService.UpdateSolvedTask: {Type: UsersModelService_Retryable_FailedToUpdateSolvedTask, Message: Failed to query database : pq: column \"user_id\" of relation \"solved_tasks\" does not exist}"},"attributes":[{"key":"error.ErrorTrace","value":{"arrayValue":{"values":[{"stringValue":"UsersModelService_Retryable_FailedToUpdateSolvedTask"},{"stringValue":"DBService_Retryable_FailedToQueryDatabase"}]}}},{"key":"error.Origin","value":{"stringValue":"UsersModelService.UpdateSolvedTask"}},{"key":"error.Message","value":{"stringValue":"Failed to query database : pq: column \"user_id\" of relation \"solved_tasks\" does not exist"}}],"traceId":"","spanId":"","eventName":"UsersModelService_Retryable_FailedToUpdateSolvedTask"}]}],"schemaUrl":"https://opentelemetry.io/schemas/1.17.0"}]}
{"resourceLogs":[{"resource":{"attributes":[{"key":"service.name","value":{"stringValue":"PragmatismWebApp.TelemetryService"}}]},"scopeLogs":[{"scope":{"name":"PragmatismWebApp.TelemetryService"},"logRecords":[{"timeUnixNano":"1744558984917122700","observedTimeUnixNano":"1744558984917122700","severityNumber":17,"severityText":"Error","body":{"stringValue":"UsersModelService.UpdateSolvedTask: {Type: UsersModelService_Retryable_FailedToUpdateSolvedTask, Message: Failed to query database : pq: column \"user_id\" does not exist}"},"attributes":[{"key":"error.ErrorTrace","value":{"arrayValue":{"values":[{"stringValue":"UsersModelService_Retryable_FailedToUpdateSolvedTask"},{"stringValue":"DBService_Retryable_FailedToQueryDatabase"}]}}},{"key":"error.Origin","value":{"stringValue":"UsersModelService.UpdateSolvedTask"}},{"key":"error.Message","value":{"stringValue":"Failed to query database : pq: column \"user_id\" does not exist"}}],"traceId":"","spanId":"","eventName":"UsersModelService_Retryable_FailedToUpdateSolvedTask"}]}],"schemaUrl":"https://opentelemetry.io/schemas/1.17.0"}]}
{"resourceLogs":[{"resource":{"attributes":[{"key":"service.name","value":{"stringValue":"PragmatismWebApp.TelemetryService"}}]},"scopeLogs":[{"scope":{"name":"PragmatismWebApp.TelemetryService"},"logRecords":[{"timeUnixNano":"1744559102986957200","observedTimeUnixNano":"1744559102986957200","severityNumber":17,"severityText":"Error","body":{"stringValue":"UsersModelService.UpdateSolvedTask: {Type: UsersModelService_Retryable_FailedToUpdateSolvedTask, Message: Failed to query database : pq: there is no unique or exclusion constraint matching the ON CONFLICT specification}"},"attributes":[{"key":"error.ErrorTrace","value":{"arrayValue":{"values":[{"stringValue":"UsersModelService_Retryable_FailedToUpdateSolvedTask"},{"stringValue":"DBService_Retryable_FailedToQueryDatabase"}]}}},{"key":"error.Origin","value":{"stringValue":"UsersModelService.UpdateSolvedTask"}},{"key":"error.Message","value":{"stringValue":"Failed to query database : pq: there is no unique or exclusion constraint matching the ON CONFLICT specification"}}],"traceId":"","spanId":"","eventName":"UsersModelService_Retryable_FailedToUpdateSolvedTask"}]}],"schemaUrl":"https://opentelemetry.io/schemas/1.17.0"}]}
